### ISSUE TITLE
How to get token?

### ISSUE THREAD

**Issue by visionarylab** [keymetrics/keymetrics-widget#3]
Hi, I consider trying up the Keymetrics free plan, 
but never able to found token to login the desktop apps.

Where can i find token?

**Comment by ItsJimi** [comment]
Hi @visionarylab ,
You can get a new token on this page (https://app.keymetrics.io/#/user/profile) by clicking on "Create new token". After token was create, you can click on green button on the right to copy the token.
If you have any questions, let me know :)
